import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:assets_dashboard/core/constants/app_colors.dart';
import 'package:assets_dashboard/core/constants/app_sizes.dart';
import 'package:assets_dashboard/core/utils/date_formatter.dart';
import 'package:assets_dashboard/data/models/employee_model.dart';
import 'package:assets_dashboard/providers/employee_provider.dart';
import 'package:assets_dashboard/providers/branch_provider.dart';

/// Add Employee Screen - Create new employee
class AddEmployeeScreen extends StatefulWidget {
  const AddEmployeeScreen({super.key});

  @override
  State<AddEmployeeScreen> createState() => _AddEmployeeScreenState();
}

class _AddEmployeeScreenState extends State<AddEmployeeScreen> {
  final _formKey = GlobalKey<FormState>();
  final _employeeIdController = TextEditingController();
  final _employeeNameController = TextEditingController();
  final _employeePhoneController = TextEditingController();
  final _employeeEmailController = TextEditingController();
  final _employeeDepartmentController = TextEditingController();
  final _employeeDesignationController = TextEditingController();
  
  String? _selectedBranch;
  String? _selectedType;
  DateTime? _selectedDOB;
  DateTime? _selectedDateOfJoining;

  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    // Load branches for dropdown
    WidgetsBinding.instance.addPostFrameCallback((_) {
      context.read<BranchProvider>().loadBranches();
    });
  }

  @override
  void dispose() {
    _employeeIdController.dispose();
    _employeeNameController.dispose();
    _employeePhoneController.dispose();
    _employeeEmailController.dispose();
    _employeeDepartmentController.dispose();
    _employeeDesignationController.dispose();
    super.dispose();
  }

  Future<void> _selectDate(BuildContext context, bool isDOB) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(1950),
      lastDate: DateTime(2100),
    );
    if (picked != null) {
      setState(() {
        if (isDOB) {
          _selectedDOB = picked;
        } else {
          _selectedDateOfJoining = picked;
        }
      });
    }
  }

  Future<void> _saveEmployee() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    // Validate all required fields
    List<String> missingFields = [];
    
    if (_selectedBranch == null || _selectedBranch!.isEmpty) {
      missingFields.add('Employee Branch');
    }
    if (_selectedType == null || _selectedType!.isEmpty) {
      missingFields.add('Employee Type');
    }
    if (_selectedDOB == null) {
      missingFields.add('Employee DOB');
    }
    if (_selectedDateOfJoining == null) {
      missingFields.add('Employee Date Of Joining');
    }

    if (missingFields.isNotEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Please fill in: ${missingFields.join(', ')}'),
          duration: const Duration(seconds: 3),
        ),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    final employee = EmployeeModel(
      id: '', // Will be auto-generated by Firestore
      employeeId: _employeeIdController.text.trim(),
      employeeName: _employeeNameController.text.trim(),
      employeeDOB: _selectedDOB!,
      employeePhoneNo: _employeePhoneController.text.trim(),
      employeeEmail: _employeeEmailController.text.trim(),
      employeeDepartment: _employeeDepartmentController.text.trim(),
      employeeDesignation: _employeeDesignationController.text.trim(),
      employeeBranch: _selectedBranch ?? '',
      employeeType: _selectedType ?? 'Full-time',
      employeeDateOfJoining: _selectedDateOfJoining!,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final success = await context.read<EmployeeProvider>().addEmployee(employee);

    setState(() {
      _isLoading = false;
    });

    if (success && mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Employee added successfully')),
      );
      Navigator.pop(context);
    } else if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            context.read<EmployeeProvider>().error ?? 'Failed to add employee',
          ),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(AppSizes.spacing32),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header
            Row(
              children: [
                IconButton(
                  icon: const Icon(Icons.arrow_back),
                  onPressed: () => Navigator.pop(context),
                ),
                const SizedBox(width: 8),
                Text(
                  'Employee Add Data',
                  style: Theme.of(context).textTheme.displayMedium?.copyWith(
                        fontSize: 32,
                        fontWeight: FontWeight.bold,
                      ),
                ),
              ],
            ),

            const SizedBox(height: AppSizes.spacing32),

            // Form
            Form(
              key: _formKey,
              child: Consumer<BranchProvider>(
                builder: (context, branchProvider, child) {
                  final branches = branchProvider.getBranchNames();
                  final types = ['Full-time', 'Part-time', 'Contract', 'Intern'];

                  return Column(
                    children: [
                      // Row 1: Employee ID and Employee Name
                      Row(
                        children: [
                          Expanded(
                            child: _buildTextField(
                              label: 'Employee Id',
                              controller: _employeeIdController,
                              validator: (value) {
                                if (value == null || value.isEmpty) {
                                  return 'Required';
                                }
                                return null;
                              },
                            ),
                          ),
                          const SizedBox(width: AppSizes.spacing24),
                          Expanded(
                            child: _buildTextField(
                              label: 'Employee Name',
                              controller: _employeeNameController,
                              validator: (value) {
                                if (value == null || value.isEmpty) {
                                  return 'Required';
                                }
                                return null;
                              },
                            ),
                          ),
                        ],
                      ),

                      const SizedBox(height: AppSizes.spacing24),

                      // Row 2: Employee DOB and Employee Phone No
                      Row(
                        children: [
                          Expanded(
                            child: _buildDateField(
                              label: 'Employee DOB*',
                              selectedDate: _selectedDOB,
                              onTap: () => _selectDate(context, true),
                            ),
                          ),
                          const SizedBox(width: AppSizes.spacing24),
                          Expanded(
                            child: _buildTextField(
                              label: 'Employee Phone No',
                              controller: _employeePhoneController,
                              keyboardType: TextInputType.phone,
                              validator: (value) {
                                if (value == null || value.isEmpty) {
                                  return 'Required';
                                }
                                return null;
                              },
                            ),
                          ),
                        ],
                      ),

                      const SizedBox(height: AppSizes.spacing24),

                      // Row 3: Employee Email and Employee Department
                      Row(
                        children: [
                          Expanded(
                            child: _buildTextField(
                              label: 'Employee Email',
                              controller: _employeeEmailController,
                              keyboardType: TextInputType.emailAddress,
                              validator: (value) {
                                if (value == null || value.isEmpty) {
                                  return 'Required';
                                }
                                return null;
                              },
                            ),
                          ),
                          const SizedBox(width: AppSizes.spacing24),
                          Expanded(
                            child: _buildTextField(
                              label: 'Employee Department',
                              controller: _employeeDepartmentController,
                              validator: (value) {
                                if (value == null || value.isEmpty) {
                                  return 'Required';
                                }
                                return null;
                              },
                            ),
                          ),
                        ],
                      ),

                      const SizedBox(height: AppSizes.spacing24),

                      // Row 4: Employee Designation and Employee Branch
                      Row(
                        children: [
                          Expanded(
                            child: _buildTextField(
                              label: 'Employee Designation',
                              controller: _employeeDesignationController,
                              validator: (value) {
                                if (value == null || value.isEmpty) {
                                  return 'Required';
                                }
                                return null;
                              },
                            ),
                          ),
                          const SizedBox(width: AppSizes.spacing24),
                          Expanded(
                            child: _buildDropdown(
                              label: 'Employee Branch*',
                              value: _selectedBranch,
                              items: branches,
                              onChanged: (value) {
                                setState(() {
                                  _selectedBranch = value;
                                });
                              },
                            ),
                          ),
                        ],
                      ),

                      const SizedBox(height: AppSizes.spacing24),

                      // Row 5: Employee Date Of Joining and Employee Type
                      Row(
                        children: [
                          Expanded(
                            child: _buildDateField(
                              label: 'Employee Date Of Joining*',
                              selectedDate: _selectedDateOfJoining,
                              onTap: () => _selectDate(context, false),
                            ),
                          ),
                          const SizedBox(width: AppSizes.spacing24),
                          Expanded(
                            child: _buildDropdown(
                              label: 'Employee Type*',
                              value: _selectedType,
                              items: types,
                              onChanged: (value) {
                                setState(() {
                                  _selectedType = value;
                                });
                              },
                            ),
                          ),
                        ],
                      ),

                      const SizedBox(height: AppSizes.spacing24),

                      const SizedBox(height: AppSizes.spacing32),

                      // Save Button
                      Align(
                        alignment: Alignment.centerLeft,
                        child: SizedBox(
                          width: 200,
                          child: ElevatedButton(
                            onPressed: _isLoading ? null : _saveEmployee,
                            style: ElevatedButton.styleFrom(
                              padding: const EdgeInsets.symmetric(
                                horizontal: AppSizes.spacing32,
                                vertical: AppSizes.spacing16,
                              ),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(AppSizes.radiusMedium),
                              ),
                            ),
                            child: _isLoading
                                ? const SizedBox(
                                    height: 20,
                                    width: 20,
                                    child: CircularProgressIndicator(
                                      strokeWidth: 2,
                                      color: Colors.white,
                                    ),
                                  )
                                : const Text(
                                    'Save',
                                    style: TextStyle(fontSize: 16),
                                  ),
                          ),
                        ),
                      ),
                    ],
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTextField({
    required String label,
    required TextEditingController controller,
    TextInputType? keyboardType,
    String? Function(String?)? validator,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: Theme.of(context).textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w500,
              ),
        ),
        const SizedBox(height: 8),
        TextFormField(
          controller: controller,
          keyboardType: keyboardType,
          validator: validator,
          decoration: InputDecoration(
            hintText: 'Placeholder',
            hintStyle: const TextStyle(color: AppColors.gray400),
            contentPadding: const EdgeInsets.symmetric(
              horizontal: AppSizes.spacing16,
              vertical: AppSizes.spacing12,
            ),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(AppSizes.radiusMedium),
              borderSide: const BorderSide(
                color: AppColors.border,
                width: AppSizes.borderThin,
              ),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildDropdown({
    required String label,
    required String? value,
    required List<String> items,
    required void Function(String?) onChanged,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: Theme.of(context).textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w500,
              ),
        ),
        const SizedBox(height: 8),
        Container(
          padding: const EdgeInsets.symmetric(
            horizontal: AppSizes.spacing16,
            vertical: AppSizes.spacing4,
          ),
          decoration: BoxDecoration(
            border: Border.all(
              color: AppColors.border,
              width: AppSizes.borderThin,
            ),
            borderRadius: BorderRadius.circular(AppSizes.radiusMedium),
          ),
          child: DropdownButton<String>(
            value: value,
            isExpanded: true,
            underline: const SizedBox(),
            hint: const Text('Placeholder', style: TextStyle(color: AppColors.gray400)),
            items: items.map((String item) {
              return DropdownMenuItem<String>(
                value: item,
                child: Text(item),
              );
            }).toList(),
            onChanged: onChanged,
          ),
        ),
      ],
    );
  }

  Widget _buildDateField({
    required String label,
    required DateTime? selectedDate,
    required VoidCallback onTap,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: Theme.of(context).textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w500,
              ),
        ),
        const SizedBox(height: 8),
        InkWell(
          onTap: onTap,
          child: Container(
            padding: const EdgeInsets.symmetric(
              horizontal: AppSizes.spacing16,
              vertical: AppSizes.spacing12,
            ),
            decoration: BoxDecoration(
              border: Border.all(
                color: AppColors.border,
                width: AppSizes.borderThin,
              ),
              borderRadius: BorderRadius.circular(AppSizes.radiusMedium),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  selectedDate != null
                      ? DateFormatter.formatDate(selectedDate)
                      : 'Placeholder',
                  style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                        color: selectedDate != null
                            ? AppColors.textPrimary
                            : AppColors.gray400,
                      ),
                ),
                const Icon(Icons.calendar_today, size: 18),
              ],
            ),
          ),
        ),
      ],
    );
  }
}
