import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:assets_dashboard/core/constants/app_colors.dart';
import 'package:assets_dashboard/core/constants/app_sizes.dart';
import 'package:assets_dashboard/core/utils/date_formatter.dart';
import 'package:assets_dashboard/data/models/asset_model.dart';
import 'package:assets_dashboard/providers/asset_provider.dart';
import 'package:assets_dashboard/providers/settings_provider.dart';
import 'package:assets_dashboard/providers/employee_provider.dart';

/// Add Asset Screen - Create new asset
class AddAssetScreen extends StatefulWidget {
  const AddAssetScreen({super.key});

  @override
  State<AddAssetScreen> createState() => _AddAssetScreenState();
}

class _AddAssetScreenState extends State<AddAssetScreen> {
  final _formKey = GlobalKey<FormState>();
  final _assetIdController = TextEditingController();
  final _nameController = TextEditingController();
  final _costController = TextEditingController();
  
  String? _selectedCategory;
  String? _selectedAssignedTo;
  String? _selectedStatus;
  String? _selectedCondition;
  DateTime? _selectedDate;
  DateTime? _selectedWarranty;

  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    // Load employees for assignee dropdown
    WidgetsBinding.instance.addPostFrameCallback((_) {
      context.read<EmployeeProvider>().loadEmployees();
    });
  }

  @override
  void dispose() {
    _assetIdController.dispose();
    _nameController.dispose();
    _costController.dispose();
    super.dispose();
  }

  Future<void> _selectDate(BuildContext context, bool isWarranty) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(2000),
      lastDate: DateTime(2100),
    );
    if (picked != null) {
      setState(() {
        if (isWarranty) {
          _selectedWarranty = picked;
        } else {
          _selectedDate = picked;
        }
      });
    }
  }

  Future<void> _saveAsset() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    // Validate all required fields
    List<String> missingFields = [];
    
    if (_selectedCategory == null || _selectedCategory!.isEmpty) {
      missingFields.add('Category');
    }
    if (_selectedAssignedTo == null || _selectedAssignedTo!.isEmpty) {
      missingFields.add('Assigned To');
    }
    if (_selectedStatus == null || _selectedStatus!.isEmpty) {
      missingFields.add('Status');
    }
    if (_selectedCondition == null || _selectedCondition!.isEmpty) {
      missingFields.add('Condition');
    }
    if (_selectedDate == null) {
      missingFields.add('Date');
    }
    if (_selectedWarranty == null) {
      missingFields.add('Warranty');
    }

    if (missingFields.isNotEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Please fill in: ${missingFields.join(', ')}'),
          duration: const Duration(seconds: 3),
        ),
      );
      return;
    }

    setState(() {
      _isLoading = true;
    });

    final asset = AssetModel(
      id: '', // Will be auto-generated by Firestore
      assetId: _assetIdController.text.trim(),
      name: _nameController.text.trim(),
      category: _selectedCategory ?? '',
      assignedTo: _selectedAssignedTo ?? '',
      date: _selectedDate!,
      cost: double.tryParse(_costController.text.trim()) ?? 0.0,
      status: _selectedStatus ?? '',
      warranty: _selectedWarranty!,
      condition: _selectedCondition ?? '',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    final success = await context.read<AssetProvider>().addAsset(asset);

    setState(() {
      _isLoading = false;
    });

    if (success && mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Asset added successfully')),
      );
      Navigator.pop(context);
    } else if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            context.read<AssetProvider>().error ?? 'Failed to add asset',
          ),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(AppSizes.spacing32),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header
            Row(
              children: [
                IconButton(
                  icon: const Icon(Icons.arrow_back),
                  onPressed: () => Navigator.pop(context),
                ),
                const SizedBox(width: 8),
                Text(
                  'Create Asset Data',
                  style: Theme.of(context).textTheme.displayMedium?.copyWith(
                        fontSize: 32,
                        fontWeight: FontWeight.bold,
                      ),
                ),
              ],
            ),

            const SizedBox(height: AppSizes.spacing32),

            // Form
            Form(
              key: _formKey,
              child: Consumer2<SettingsProvider, EmployeeProvider>(
                builder: (context, settingsProvider, employeeProvider, child) {
                  final categories = settingsProvider.assetCategories;
                  final statuses = settingsProvider.assetStatuses;
                  final employees = employeeProvider.getEmployeeNames();
                  final conditions = ['Good', 'Fair', 'Poor'];

                  return Column(
                    children: [
                      // Row 1: Asset ID and Category
                      Row(
                        children: [
                          Expanded(
                            child: _buildTextField(
                              label: 'Asset Id*',
                              controller: _assetIdController,
                              validator: (value) {
                                if (value == null || value.isEmpty) {
                                  return 'Required';
                                }
                                return null;
                              },
                            ),
                          ),
                          const SizedBox(width: AppSizes.spacing24),
                          Expanded(
                            child: _buildDropdown(
                              label: 'Category*',
                              value: _selectedCategory,
                              items: categories,
                              onChanged: (value) {
                                setState(() {
                                  _selectedCategory = value;
                                });
                              },
                            ),
                          ),
                        ],
                      ),

                      const SizedBox(height: AppSizes.spacing24),

                      // Row 2: Name and Assigned To
                      Row(
                        children: [
                          Expanded(
                            child: _buildTextField(
                              label: 'Name*',
                              controller: _nameController,
                              validator: (value) {
                                if (value == null || value.isEmpty) {
                                  return 'Required';
                                }
                                return null;
                              },
                            ),
                          ),
                          const SizedBox(width: AppSizes.spacing24),
                          Expanded(
                            child: _buildDropdown(
                              label: 'Assigned To*',
                              value: _selectedAssignedTo,
                              items: employees,
                              onChanged: (value) {
                                setState(() {
                                  _selectedAssignedTo = value;
                                });
                              },
                            ),
                          ),
                        ],
                      ),

                      const SizedBox(height: AppSizes.spacing24),

                      // Row 3: Date and Cost
                      Row(
                        children: [
                          Expanded(
                            child: _buildDateField(
                              label: 'Date*',
                              selectedDate: _selectedDate,
                              onTap: () => _selectDate(context, false),
                            ),
                          ),
                          const SizedBox(width: AppSizes.spacing24),
                          Expanded(
                            child: _buildTextField(
                              label: 'Cost*',
                              controller: _costController,
                              keyboardType: TextInputType.number,
                              validator: (value) {
                                if (value == null || value.isEmpty) {
                                  return 'Required';
                                }
                                if (double.tryParse(value) == null) {
                                  return 'Invalid number';
                                }
                                return null;
                              },
                            ),
                          ),
                        ],
                      ),

                      const SizedBox(height: AppSizes.spacing24),

                      // Row 4: Status and Warranty
                      Row(
                        children: [
                          Expanded(
                            child: _buildDropdown(
                              label: 'Status*',
                              value: _selectedStatus,
                              items: statuses,
                              onChanged: (value) {
                                setState(() {
                                  _selectedStatus = value;
                                });
                              },
                            ),
                          ),
                          const SizedBox(width: AppSizes.spacing24),
                          Expanded(
                            child: _buildDateField(
                              label: 'Warranty*',
                              selectedDate: _selectedWarranty,
                              onTap: () => _selectDate(context, true),
                            ),
                          ),
                        ],
                      ),

                      const SizedBox(height: AppSizes.spacing24),

                      // Row 5: Condition
                      Row(
                        children: [
                          Expanded(
                            child: _buildDropdown(
                              label: 'Condition*',
                              value: _selectedCondition,
                              items: conditions,
                              onChanged: (value) {
                                setState(() {
                                  _selectedCondition = value;
                                });
                              },
                            ),
                          ),
                          const Expanded(child: SizedBox()),
                        ],
                      ),

                      const SizedBox(height: AppSizes.spacing32),

                      // Create Button
                      Align(
                        alignment: Alignment.centerLeft,
                        child: SizedBox(
                          width: 200,
                          child: ElevatedButton(
                            onPressed: _isLoading ? null : _saveAsset,
                            style: ElevatedButton.styleFrom(
                              padding: const EdgeInsets.symmetric(
                                horizontal: AppSizes.spacing32,
                                vertical: AppSizes.spacing16,
                              ),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(AppSizes.radiusMedium),
                              ),
                            ),
                            child: _isLoading
                                ? const SizedBox(
                                    height: 20,
                                    width: 20,
                                    child: CircularProgressIndicator(
                                      strokeWidth: 2,
                                      color: Colors.white,
                                    ),
                                  )
                                : const Text(
                                    'Create',
                                    style: TextStyle(fontSize: 16),
                                  ),
                          ),
                        ),
                      ),
                    ],
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTextField({
    required String label,
    required TextEditingController controller,
    TextInputType? keyboardType,
    String? Function(String?)? validator,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: Theme.of(context).textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w500,
              ),
        ),
        const SizedBox(height: 8),
        TextFormField(
          controller: controller,
          keyboardType: keyboardType,
          validator: validator,
          decoration: InputDecoration(
            contentPadding: const EdgeInsets.symmetric(
              horizontal: AppSizes.spacing16,
              vertical: AppSizes.spacing12,
            ),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(AppSizes.radiusMedium),
              borderSide: const BorderSide(
                color: AppColors.border,
                width: AppSizes.borderThin,
              ),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildDropdown({
    required String label,
    required String? value,
    required List<String> items,
    required void Function(String?) onChanged,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: Theme.of(context).textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w500,
              ),
        ),
        const SizedBox(height: 8),
        Container(
          padding: const EdgeInsets.symmetric(
            horizontal: AppSizes.spacing16,
            vertical: AppSizes.spacing4,
          ),
          decoration: BoxDecoration(
            border: Border.all(
              color: AppColors.border,
              width: AppSizes.borderThin,
            ),
            borderRadius: BorderRadius.circular(AppSizes.radiusMedium),
          ),
          child: DropdownButton<String>(
            value: value,
            isExpanded: true,
            underline: const SizedBox(),
            hint: const Text('Select'),
            items: items.map((String item) {
              return DropdownMenuItem<String>(
                value: item,
                child: Text(item),
              );
            }).toList(),
            onChanged: onChanged,
          ),
        ),
      ],
    );
  }

  Widget _buildDateField({
    required String label,
    required DateTime? selectedDate,
    required VoidCallback onTap,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: Theme.of(context).textTheme.titleMedium?.copyWith(
                fontWeight: FontWeight.w500,
              ),
        ),
        const SizedBox(height: 8),
        InkWell(
          onTap: onTap,
          child: Container(
            padding: const EdgeInsets.symmetric(
              horizontal: AppSizes.spacing16,
              vertical: AppSizes.spacing12,
            ),
            decoration: BoxDecoration(
              border: Border.all(
                color: AppColors.border,
                width: AppSizes.borderThin,
              ),
              borderRadius: BorderRadius.circular(AppSizes.radiusMedium),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  selectedDate != null
                      ? DateFormatter.formatDate(selectedDate)
                      : 'Select date',
                  style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                        color: selectedDate != null
                            ? AppColors.textPrimary
                            : AppColors.gray600,
                      ),
                ),
                const Icon(Icons.calendar_today, size: 18),
              ],
            ),
          ),
        ),
      ],
    );
  }
}
